_BASE_: "Base-CTW1500.yaml"
MODEL:
  WEIGHTS: '/data/pretrained/pytorch/AdelaiDet/phoenix-bohan/output/batext/pretrain/attn_R_18-FPN_SyncBN-FixFPN/model_final.pth'
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "NO-ReLU"
    #NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "NO-ReLU"
    #NORM: "SyncBN-ReLU"
  BATEXT:
    NORM: "NO"
    #NORM: "SyncBN"
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (160000, 220000)
  MAX_ITER: 260000
  CHECKPOINT_PERIOD: 20000
#INPUT:
#  MIN_SIZE_TEST: 800
#  MAX_SIZE_TEST: 1400
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/batext/ctw1500/attn_R_18-FPN_SyncBN-FixFPN-speed"

