_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/resnet18_w32a32.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  SOLOV2:
    NUM_INSTANCE_CONVS: 4
    USE_DCN_IN_INSTANCE: False
DATASETS:
  TRAIN: ("coco_2017_train",)
OUTPUT_DIR: output/solov2/SOLOv2_R18_800_1x-Full_SyncBN
