_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "output/fcos/R_18_1x-Full-SyncBN-FixFPN/model_final.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN-ReLU"
    #USE_RELU: True
  FCOS:
    NORM: "SyncBN"
  # open the mix precision if GPU memory not enough. Known issue: fp16 conflicts with SyncBN for multi GPU training
  #fp16: True
  QUANTIZATION:
    scope: [
            # backbone
            'backbone',
            # Head
            'proposal_generator',
           ]
    keyword: ["debug", "dorefa", "lsq"]
    fm_enable: True 
    wt_enable: True 
    padding_after_quant: True
    fm_bit: 4.0
    wt_bit: 4.0
    fm_boundary: 1.0
    wt_boundary: 1.0
    wt_quant_group: 1
    wt_adaptive: "var-mean"
    policy: 'configs/FCOS-Detection/policy-fcos-r18-fixpoint.txt'
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R_18_1x-Full_SyncBN-FixFPN-FixPoint-lsq-4bit"
