_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/resnet18_w32a32.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "BN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  BATEXT:
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (320000, 440000)
  MAX_ITER: 520000
  CHECKPOINT_PERIOD: 40000
TEST:
  EVAL_PERIOD: 40000
OUTPUT_DIR: "output/batext/pretrain/attn_R_18-dihl"
