_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet50/resnet50-19c8e357.pth"
  RESNETS:
    DEPTH: 50
    RES2_OUT_CHANNELS: 256
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  FCOS:
    NORM: "SyncBN"
  # turn on for mix precision training
  #fp16: True
  BATEXT:
    NORM: "SyncBN"
    RECOGNIZER_NORM: "SyncBN" 
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (160000, 220000)
  MAX_ITER: 260000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "output/batext/pretrain/attn_R_50-Full_SyncBN"
