_BASE_: "Base-550.yaml"
MODEL:
  WEIGHTS: "weights/det-resnet18/resnet18_w32a32.pth"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "SyncBN"
    USE_RELU: True
  FCOS:
    NORM: "SyncBN"
  # open the mix precision if GPU memory not enough
  #fp16: True
OUTPUT_DIR: "output/blendmask/550_R_18_1x_full_syncbn"
